---
title: "Ejercicio práctico Rmarkdown"
author:
    - names: "Patricia Camacho"

date: "`r Sys.Date()`" 
output: 
    distill::distill_article:
        highlight: kate
        code_folding: false  
        toc: true     
        toc_depth: 3
        css: styles.css         
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE)

# Cargar los paquetes necesarios
library(tidyr)
library(dplyr)

# Cargar los datos
data <- read.csv("top10s.csv")

```

# Informe hits de Spotify 2010-2019

## Datos

Top Spotify Songs 2010-2019

<https://www.kaggle.com/datasets/leonardopena/top-spotify-songs-from-20102019-by-year/>

## Artistas con más éxitos

```{r top_artists}

data %>% dplyr::count(artist) %>% arrange(desc(n)) %>% head()

```

## Estilos con más éxitos

```{r top_genres}

data %>% dplyr::count(top.genre) %>% arrange(desc(n)) %>% head()

```

## Tendencia de la duración de los hits

```{r duration_trend, fig.width=8, fig.height=6}

plot(dur ~ year, data = data, main = "Tendencia de la duración de los hits",
     xlab = "Año", ylab = "Duración (segundos)")
abline(lm(dur ~ year, data = data), col = "blue", lwd = 2)

modelo <- lm(dur ~ year, data = data)
pendiente <- coef(modelo)[2]

if (pendiente > 0) {
  mensaje <- "Las canciones se han vuelto más largas con el tiempo."
} else if (pendiente < 0) {
  mensaje <- "Las canciones han reducido su duración con los años."
} else {
  mensaje <- "No hay una tendencia clara en la duración de las canciones."
}


cat(mensaje, "\n")

```
